# @package algorithm
defaults:
  - ../lstm_base
  - apple_base
  - override /agent/image_encoder@agent.image_encoder: vit
  - _self_

batch_size: 8

update_to_data_ratio: 0.4586235468898557
initial_utd: 0.3295780080523606
utd_warmup_steps_rel: 0.5

actor_optimizer:
  type: ADAMW
  learning_rate:
    value: 0.00018924232663732112
  max_grad_norm: 7989.072049990323

critic_optimizer:
  type: ADAMW
  learning_rate:
    value: 0.0004085511215266315
  max_grad_norm: 7989.072049990323

alpha_optimizer:
  type: ADAMW
  learning_rate:
    value: 0.0004085511215266315
  max_grad_norm: 7989.072049990323
