# @package algorithm
defaults:
  - ../lstm_base
  - apple_base  # Ordering to ensure that CrossQ has the last say in agent configuration
  - _self_

batch_size: 32

update_to_data_ratio: 0.6151014585301664
initial_utd: 3.1855833418690715
utd_warmup_steps_rel: 1.0
critic_norm: LAYER_NORM

actor_optimizer:
  type: ADAMW
  learning_rate:
    value: 3.996343128179805e-06
  max_grad_norm: 0.10003437013029032

critic_optimizer:
  type: ADAMW
  learning_rate:
    value: 8.605766697725939e-05
  max_grad_norm: 0.10003437013029032

alpha_optimizer:
  type: ADAMW
  learning_rate:
    value: 8.605766697725939e-05
  max_grad_norm: 0.10003437013029032
